# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='space.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkstatus',
            name='label',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='space.Checklist'),
        ),
    ]
