# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='space.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
