# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_auto_20181025_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkstatus',
            name='label',
        ),
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='space.CheckStatus'),
        ),
    ]
